config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:index, :new, :create]
  end
  resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient,
    message: "a given cocktail/ingredient couple is unique" }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    if params[:search]
      @cocktails = Cocktail.where('name like ?', "%#{params[:search]}%")
    else
    @cocktails = Cocktail.all
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: @cocktail)

    # @reviews = Review.where(cocktail: @cocktail)
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :dose_id, :ingredient_id, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @cocktail = Cocktail.find(params[:cocktail_id])
    @doses = Dose.where(cocktail_id: @cocktail)
  end

  def new
    # we need @cocktail in our `simple_form_for`
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @name_ingredients = []
    Ingredient.all.each do |ingredient|
      @name_ingredients << ingredient.name
    end
  end

  def create
    @dose = Dose.new
    @dose.description = params["dose"]["description"]
    # we need `cocktail_id` to associate dose with corresponding cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @name_ingredients = []
    Ingredient.all.each do |ingredient|
      @name_ingredients << ingredient.name
    end
    @ingredient_param = params["dose"]["ingredient"]
    @ingredient_array = Ingredient.where(name: @ingredient_param)
    @ingredient_array.each { |ingredient| @dose.ingredient = ingredient }
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params["id"])
    @dose.delete
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Mister Cocktail</h1>

 <form class="form-inline">
  <label for="search"></label><br>
  <input type="text" id="search" name="search" placeholder="Search for a cocktail"><br>
  <input type="submit" value="Submit">
</form>

<% @cocktails.each do |cocktail| %>
<h2>
  <%= link_to cocktail.name, cocktail_path(cocktail) %>
</h2>
<% end %>

<p>
<%= link_to "Ajoutez votre cocktail", new_cocktail_path %>
</p>

<%= cl_image_tag("https://res.cloudinary.com/leoc/image/upload/v1573818925/cqdtlulmx5zsoda1hdfk.jpg", width: 400, crop: :fill) %>

app/views/cocktails/new.html.erb
<h1>Ajoutez un cocktail à la collection !</h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Ajoutez un cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<h1>Découvrez la recette de votre cocktail</h1>

<%= @cocktail.name %>
<% if @cocktail.photo.attached? %>
<%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
<% end %>


<% @doses.each do |dose| %>
<p>
<%= dose.ingredient.name %>
<%= dose.description %>
</p>
<% end %>

<p> <%= link_to "Regardez la recette précise de votre cocktail", cocktail_doses_path(@cocktail) %> </p> <br>

<p> <%= link_to "Retournez voir les autres cocktails", root_path %> </p>

app/views/doses/index.html.erb
<h1>Les ingrédients de votre cocktail</h1>

<% @doses.each do |dose| %>
<h2>
  <%= dose.ingredient.name %>
  <%= dose.description %>
  <% @dose = dose %>
  <p><%= link_to "Supprimer cette dose", dose_path(@dose), method: :delete, data: { confirm: "Sure?" } %></p>
</h2>
<% end %>


<%= link_to "Ajoutez un nouveau ingrédient à votre cocktail", new_cocktail_dose_path(@cocktail) %>

app/views/doses/new.html.erb
<h1>Ajoutez une dose à votre cocktail</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.select :ingredient, collection: @name_ingredients %>
  <%= f.submit "ajoutez une dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
   <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1551024709-8f23befc6f87?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2625&q=80);">
     <div class="container">
       <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
       <p>Change your life and learn to code at one of our campuses around the world.</p>
       <a class="btn btn-flat" href="#">Apply now</a>
     </div>
   </div>


    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>